/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controldeclientes;

import static controldeclientes.VentanaCargarDeuda.ID_Deudor;
import static controldeclientes.VentanaCargarDeuda.apellido;
import static controldeclientes.VentanaCargarDeuda.nombre;
import java.awt.HeadlessException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class VentanaCargarPago extends javax.swing.JFrame {
 public static int ID_Deudor;
    public static String nombre, apellido ; 
  
  
    /**
     * Creates new form VentanaCargarPago
     */
    public VentanaCargarPago() {
        
        
        initComponents();
       this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
        VentanaBuscarCliente cr = new VentanaBuscarCliente();
        
        this.nombre = cr.nombreSalida;
        this.apellido = cr.apellidoSalida;
        this.ID_Deudor = cr.ID_Cliente; 
        
        labelNombre.setText(nombre +" "+apellido+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoMonto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        botonCargarPago = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoSalida = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMontoActionPerformed(evt);
            }
        });
        getContentPane().add(campoMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripcion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        botonVolver.setBackground(new java.awt.Color(216, 21, 60));
        botonVolver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 80, 30));

        botonCargarPago.setBackground(new java.awt.Color(216, 21, 60));
        botonCargarPago.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonCargarPago.setForeground(new java.awt.Color(255, 255, 255));
        botonCargarPago.setText("Cargar Pago");
        botonCargarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 130, 40));

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        campoDescripcion.setMinimumSize(new java.awt.Dimension(6, 20));
        jScrollPane1.setViewportView(campoDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 310, 270));

        jScrollPane2.setBackground(new java.awt.Color(216, 21, 60));

        campoSalida.setEditable(false);
        campoSalida.setBackground(new java.awt.Color(216, 21, 60));
        campoSalida.setColumns(20);
        campoSalida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campoSalida.setForeground(new java.awt.Color(255, 255, 255));
        campoSalida.setRows(5);
        campoSalida.setText("Ingrese los datos para registrar \nel pago del cliente.");
        jScrollPane2.setViewportView(campoSalida);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 290, 270));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controldeclientes/Imagenes/Mushroom_1UP_Icon_64.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese los datos del Pago");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cliente: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("jLabel8");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("©TheBlackPeople");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 90, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controldeclientes/Imagenes/Fondo.jpg"))); // NOI18N
        jLabel1.setText("©TheBlackPeople");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 749, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
               VerDeuda ventanaAnterior = new VerDeuda();
               ventanaAnterior.setVisible(true);
               this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void campoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMontoActionPerformed

    private void botonCargarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarPagoActionPerformed
    int mes, año ,dia ; 
            Calendar fecha = new GregorianCalendar();
              año = fecha.get(Calendar.YEAR);
              mes = fecha.get(Calendar.MONTH);
              dia = fecha.get(Calendar.DAY_OF_MONTH);
              
              int  id_Deuda, montoD , montoP;
        if(!"".equals(campoMonto.getText()) && !"".equals(campoDescripcion.getText())){
       
           
        
                 montoP = parseInt(campoMonto.getText());
                 try{
                 Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sistemaclientes","root","");
                  PreparedStatement pst = cn.prepareStatement("insert into pagos values(?,?,?,?,?)");
             
                  pst.setInt(1, ID_Deudor);
                  pst.setString(2, ""+dia+"/"+(mes+1)+"/"+año+"");
                  pst.setInt(3,parseInt(campoMonto.getText().trim()));
                  pst.setString(4, campoDescripcion.getText());
                  pst.setInt(5,0);
                  pst.executeUpdate();
                 
                 }catch(SQLException e){JOptionPane.showInputDialog(null, "Error en la carga del pago");}
                  
                 try{
                     Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sistemaclientes","root","");
                 
                 PreparedStatement pst1 = cn.prepareStatement("select * from deduas2 where ID_Deudor=?");
                  pst1.setInt(1,ID_Deudor);
           
                  ResultSet result = pst1.executeQuery();
                  
                   ListaDeudas lista = new ListaDeudas();
           if(result.next()){
               
              do{
               id_Deuda= result.getInt(5);   
               montoD = result.getInt(3);
            
           
               if(montoD == montoP){
                  montoP -= montoD;
                  
                   
                   lista.Insertar(id_Deuda, montoD,"1", montoP);
                   
              
               
               }else{
                   if(montoD < montoP){
                        montoP -= montoD;
                        
                       lista.Insertar(id_Deuda, montoD,"1" , montoP);
                         
                          
                          
                          
                   }else{
                        montoD -= montoP;
                          lista.Insertar(id_Deuda, montoD,"2",montoD);
                          
                     
                   }
               
               
               }
              }while(result.next() || montoP <= 0);
              
              
              lista.ActualizarBD();
               
               JOptionPane.showMessageDialog(null,"Se Registro y Desconto perfectamente el pago");
               
           
           }else{
           JOptionPane.showMessageDialog(null, "El Cliente no tiene Deudas que Pagar");
           }
             
                  campoSalida.setText("");
                  campoSalida.setText("Se registro el pago de "+nombre+" "+apellido+ "\n\n"
                                      +"Fecha: "+dia+"/"+mes+"/"+año+"\n"
                                      +"Monto: "+campoMonto.getText()+"\n"
                                      +"Descripcion: "+campoDescripcion.getText()+"\n\n" );
                  
                  
                  
                  
                  
                  
                  
                  campoMonto.setText("");
                  campoDescripcion.setText("");
                  
                  
                  
                  
              }catch(SQLException e){JOptionPane.showMessageDialog(null,"Error en la coneccion con la base de datos final");} 
        }else{JOptionPane.showMessageDialog(null,"Debe completar todos los campos para registrar el pago");}        
    }//GEN-LAST:event_botonCargarPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCargarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCargarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCargarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCargarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCargarPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarPago;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoMonto;
    private javax.swing.JTextArea campoSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
