/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controldeclientes;

import static controldeclientes.VerDeuda.ID_Cliente;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class ventanaDecision extends javax.swing.JFrame {

    /**
     * Creates new form ventanaDecision
     */
    public ventanaDecision() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botonEliminarCliente = new javax.swing.JButton();
        botonBuscarCliente = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoSalida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Que desea hacer?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 340, 60));

        botonEliminarCliente.setBackground(new java.awt.Color(216, 21, 60));
        botonEliminarCliente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        botonEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarCliente.setText("Eliminar Cliente");
        botonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 30));

        botonBuscarCliente.setBackground(new java.awt.Color(216, 21, 60));
        botonBuscarCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarCliente.setText("Buscar Cliente");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 140, 30));

        botonVolver.setBackground(new java.awt.Color(216, 21, 60));
        botonVolver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 80, 30));

        jButton1.setBackground(new java.awt.Color(216, 21, 60));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Nuevo Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 30));

        jScrollPane1.setBackground(new java.awt.Color(216, 21, 60));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        campoSalida.setEditable(false);
        campoSalida.setBackground(new java.awt.Color(216, 21, 60));
        campoSalida.setColumns(20);
        campoSalida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campoSalida.setForeground(new java.awt.Color(255, 255, 255));
        campoSalida.setRows(5);
        campoSalida.setText("Ayuda para Usuario\n\n+Nuevo Cliente:\n\tIngresando los\n\tdatos crearas un nuevo \n\tcliente y lo guardaras.\n\n+Eliminar Cliente: \n\tBusca por Nombre y \n\tApellido al cliente,\n\tpara eliminarlo.\n\n+Buscar Cliente:\n\tPuedes Buscar a un\n\tun cliente, para ver\n\tsu deuda asociada.");
        jScrollPane1.setViewportView(campoSalida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 260, 270));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controldeclientes/Imagenes/Mushroom_1UP_Icon_64.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 70));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("©TheBlackPeople");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, 20));

        jButton2.setBackground(new java.awt.Color(216, 21, 60));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Todos los Clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 30));

        jLabel1.setBackground(new java.awt.Color(216, 21, 60));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controldeclientes/Imagenes/Fondo.jpg"))); // NOI18N
        jLabel1.setText("©TheBlackPeople");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    VentanaNuevoCliente ventanaNuevoCliente = new VentanaNuevoCliente();
        ventanaNuevoCliente.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        Inicio ventanaInicio = new Inicio();
        ventanaInicio.setVisible(true);
    this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarClienteActionPerformed
        VentanaEliminar ventanaelim = new VentanaEliminar();
            ventanaelim.setVisible(true);
            this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarClienteActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
    VentanaBuscarCliente ventanaSig = new VentanaBuscarCliente();
        ventanaSig.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           campoSalida.setText(""); 
     String salida = "";
     
     try{
           Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sistemaclientes","root","");
           PreparedStatement pst = cn.prepareStatement("select * from clientes_1 order by Apellido");
          
           
           ResultSet result = pst.executeQuery();
           
           
           
           if(result.next()){
                  salida+= ("Nombre\t"+"Apellido\t"+"Telefono\t"+" Correo/Face\t "+"\n\n");
                 do{
                  salida +=  (result.getString(1)+"\t"+result.getString(2)+"\t"+result.getString(3)+"\t"+result.getString(4)+"\n\n");
                   
                     
                 }while(result.next());
                 
                    campoSalida.setText(salida);
                
       
             
           
           }else{
                    campoSalida.setText("No Hay Clientes");
           }
       
       }catch(Exception e){JOptionPane.showMessageDialog(null, "No se conecta a la base de datos");}     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boolean tbotonNuevoCliente = true;
                new ventanaDecision().setVisible(tbotonNuevoCliente);          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextArea campoSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
